DROP TABLE IF EXISTS news_articles CASCADE;
DROP TABLE IF EXISTS live_scores CASCADE;
DROP TABLE IF EXISTS predictions CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS admin_users CASCADE;
DELETE FROM schema_migrations WHERE id = '001';
